# General

git:
	git config --global user.email "carlborgas@gmail.com"
	git config --global user.name "Carl Borgas"
	git config --global alias.st 'status'
	git config --global alias.ll 'log --oneline'
	git config --global alias.last 'log -1 HEAD --stat'
	git config --global alias.cm 'commit -m'
	git config --global alias.d 'diff'
	git config --global alias.gl 'config --global -l'

tmux:
	sudo apt-get install tmux

# Languages

rust:	
	# Install rust
	$ curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh

python:
	# Install python
	sudo ln -s /usr/bin/python3 /usr/bin/python

# Apps

discord:
	# Install discord
	sudo apt update
	sudo apt install gdebi-core wget
	wget -O ~/discord.deb "https://discordapp.com/api/download?platform=linux&format=deb"
	sudo gdebi ~/discord.deb 

